# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y   +=  alsps.o
obj-y   +=  alsps_factory.o
obj-y   +=  aal_control.o

#prize-add sensor-pengzhipeng-20190419-start
obj-$(CONFIG_MTK_STK3332_V2000)	+=  stk3332_v2000/
#prize-add sensor-pengzhipeng-20190419-end

#prize added by huarui, sensor driver, 20190111-start
#prize added by huarui, sensor driver, 20190111-end
